// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxMaQB3HCnXLOY7oMHZZo3NkoCHjCnVM',
    appId: '1:45361321160:android:ea488aa4e951b82ef241fd',
    messagingSenderId: '45361321160',
    projectId: 'martfood-app',
    databaseURL: 'https://martfood-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'martfood-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6QGUlJKrywRVPx9065ukpOI6u6tKnlI',
    appId: '1:45361321160:ios:e6ae40d2dfa17130f241fd',
    messagingSenderId: '45361321160',
    projectId: 'martfood-app',
    databaseURL: 'https://martfood-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'martfood-app.firebasestorage.app',
    iosClientId: '45361321160-isflqc9c0lblgdane16vqhj26st7amo3.apps.googleusercontent.com',
    iosBundleId: 'com.martfood.app',
  );

}
